spring:
  application:
    name: bbgs-admin
  profiles:
    active: dev #默认为开发环境
server:
  port: 8080

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:top/**/mapper/*.xml


redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

jwt:
  secret: mall-admin-secretmall-admin-secret
  tokenHeader: Authorization #JWT存储的请求头
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头