package top.himcs.bbgs.mbg.model;

import java.io.Serializable;

public class SystemMenu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.parent_id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.level
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.sort
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.title
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.name
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_menu
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.id
     *
     * @return the value of system_menu.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.id
     *
     * @param id the value for system_menu.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.parent_id
     *
     * @return the value of system_menu.parent_id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.parent_id
     *
     * @param parentId the value for system_menu.parent_id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.level
     *
     * @return the value of system_menu.level
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.level
     *
     * @param level the value for system_menu.level
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.sort
     *
     * @return the value of system_menu.sort
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.sort
     *
     * @param sort the value for system_menu.sort
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.title
     *
     * @return the value of system_menu.title
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.title
     *
     * @param title the value for system_menu.title
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.name
     *
     * @return the value of system_menu.name
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.name
     *
     * @param name the value for system_menu.name
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", parentId=").append(parentId);
        sb.append(", level=").append(level);
        sb.append(", sort=").append(sort);
        sb.append(", title=").append(title);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}