package top.himcs.bbgs.mbg.model;

import java.io.Serializable;

public class SystemRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_role.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_role.role_name
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_role.level
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private Byte level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_role.status
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_role
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_role.id
     *
     * @return the value of system_role.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_role.id
     *
     * @param id the value for system_role.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_role.role_name
     *
     * @return the value of system_role.role_name
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_role.role_name
     *
     * @param roleName the value for system_role.role_name
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_role.level
     *
     * @return the value of system_role.level
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_role.level
     *
     * @param level the value for system_role.level
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_role.status
     *
     * @return the value of system_role.status
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_role.status
     *
     * @param status the value for system_role.status
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleName=").append(roleName);
        sb.append(", level=").append(level);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}