package top.himcs.bbgs.mbg.model;

import java.io.Serializable;

public class SystemAdmin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_admin.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_admin.account
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_admin.pwd
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_admin.status
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_admin.is_del
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private Byte isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_admin
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_admin.id
     *
     * @return the value of system_admin.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_admin.id
     *
     * @param id the value for system_admin.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_admin.account
     *
     * @return the value of system_admin.account
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_admin.account
     *
     * @param account the value for system_admin.account
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_admin.pwd
     *
     * @return the value of system_admin.pwd
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_admin.pwd
     *
     * @param pwd the value for system_admin.pwd
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_admin.status
     *
     * @return the value of system_admin.status
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_admin.status
     *
     * @param status the value for system_admin.status
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_admin.is_del
     *
     * @return the value of system_admin.is_del
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public Byte getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_admin.is_del
     *
     * @param isDel the value for system_admin.is_del
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setIsDel(Byte isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_admin
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", account=").append(account);
        sb.append(", pwd=").append(pwd);
        sb.append(", status=").append(status);
        sb.append(", isDel=").append(isDel);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}