package top.himcs.bbgs.mbg.model;

import java.io.Serializable;

public class SystemResourceCategory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_resource_category.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_resource_category.name
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_resource_category.sort
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_resource_category
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_resource_category.id
     *
     * @return the value of system_resource_category.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_resource_category.id
     *
     * @param id the value for system_resource_category.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_resource_category.name
     *
     * @return the value of system_resource_category.name
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_resource_category.name
     *
     * @param name the value for system_resource_category.name
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_resource_category.sort
     *
     * @return the value of system_resource_category.sort
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_resource_category.sort
     *
     * @param sort the value for system_resource_category.sort
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource_category
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", sort=").append(sort);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}