package top.himcs.bbgs.mbg.model;

import java.io.Serializable;

public class SystemResource implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_resource.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_resource.name
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_resource.url
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_resource.description
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_resource.category_id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private String categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_resource
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_resource.id
     *
     * @return the value of system_resource.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_resource.id
     *
     * @param id the value for system_resource.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_resource.name
     *
     * @return the value of system_resource.name
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_resource.name
     *
     * @param name the value for system_resource.name
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_resource.url
     *
     * @return the value of system_resource.url
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_resource.url
     *
     * @param url the value for system_resource.url
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_resource.description
     *
     * @return the value of system_resource.description
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_resource.description
     *
     * @param description the value for system_resource.description
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_resource.category_id
     *
     * @return the value of system_resource.category_id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_resource.category_id
     *
     * @param categoryId the value for system_resource.category_id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", url=").append(url);
        sb.append(", description=").append(description);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}