package top.himcs.bbgs.mbg.model;

import java.io.Serializable;

public class SystemRoleResourceRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_role_resource_relation.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_role_resource_relation.role_id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_role_resource_relation.resource_id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private Integer resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_role_resource_relation
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_role_resource_relation.id
     *
     * @return the value of system_role_resource_relation.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_role_resource_relation.id
     *
     * @param id the value for system_role_resource_relation.id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_role_resource_relation.role_id
     *
     * @return the value of system_role_resource_relation.role_id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_role_resource_relation.role_id
     *
     * @param roleId the value for system_role_resource_relation.role_id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_role_resource_relation.resource_id
     *
     * @return the value of system_role_resource_relation.resource_id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_role_resource_relation.resource_id
     *
     * @param resourceId the value for system_role_resource_relation.resource_id
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_resource_relation
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", resourceId=").append(resourceId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}