package top.himcs.bbgs.mbg.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.himcs.bbgs.mbg.model.SystemMenu;
import top.himcs.bbgs.mbg.model.SystemMenuExample;

public interface SystemMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    long countByExample(SystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int deleteByExample(SystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int insert(SystemMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int insertSelective(SystemMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    List<SystemMenu> selectByExample(SystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    SystemMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") SystemMenu record, @Param("example") SystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int updateByExample(@Param("record") SystemMenu record, @Param("example") SystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int updateByPrimaryKeySelective(SystemMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int updateByPrimaryKey(SystemMenu record);
}