package top.himcs.bbgs.mbg.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.himcs.bbgs.mbg.model.SystemRoleMenuRelation;
import top.himcs.bbgs.mbg.model.SystemRoleMenuRelationExample;

public interface SystemRoleMenuRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_menu_relation
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    long countByExample(SystemRoleMenuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_menu_relation
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int deleteByExample(SystemRoleMenuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_menu_relation
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_menu_relation
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int insert(SystemRoleMenuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_menu_relation
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int insertSelective(SystemRoleMenuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_menu_relation
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    List<SystemRoleMenuRelation> selectByExample(SystemRoleMenuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_menu_relation
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    SystemRoleMenuRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_menu_relation
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") SystemRoleMenuRelation record, @Param("example") SystemRoleMenuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_menu_relation
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int updateByExample(@Param("record") SystemRoleMenuRelation record, @Param("example") SystemRoleMenuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_menu_relation
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int updateByPrimaryKeySelective(SystemRoleMenuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_menu_relation
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int updateByPrimaryKey(SystemRoleMenuRelation record);
}