package top.himcs.bbgs.mbg.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.himcs.bbgs.mbg.model.SystemResource;
import top.himcs.bbgs.mbg.model.SystemResourceExample;

public interface SystemResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    long countByExample(SystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int deleteByExample(SystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int insert(SystemResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int insertSelective(SystemResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    List<SystemResource> selectByExample(SystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    SystemResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") SystemResource record, @Param("example") SystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int updateByExample(@Param("record") SystemResource record, @Param("example") SystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int updateByPrimaryKeySelective(SystemResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_resource
     *
     * @mbg.generated Thu Sep 03 13:43:58 CST 2020
     */
    int updateByPrimaryKey(SystemResource record);
}